### ISSUE TITLE
Feature Request: More work time options

### ISSUE THREAD

**Issue by meseck** [bernardini687/playdate-focus#1]
Hey there,
thanks for this awesome minimalist app. I really like it! 🙇 

Feature Request: 
It would be very nice if there were more options for working time, so the app becomes a little bit more flexible.

Question to Contributions:
I would also like to use this issue to ask you if you are generally open for adding/adjusting some features and if you are open for contributions? It would be helpful if you could add a license and update the readme file to make this clearer for anyone who wants to open some PRs in the future.

Thank you for your time!

**Comment by bernardini687** [comment]
Hello 👋 
thanks, really appreciated!

I wanted to work on the app again and your request looks like the perfect excuse to get back to it.
What other working time options are you thinking about?

I always welcome any kind of feedback but I haven't thought about open source contributions yet.
I'll think about that, thanks for the interest!

**Comment by meseck** [comment]
Perhaps 15 to 60 min in 5 min steps would be good for most people?
Personally, I use a 50/10 interval.

I have two more little ideas, do you want me to open two more issues? You can close them if you are not interested in implementing them, no bad feelings. It would also be visible that these features have already been requested.

**Comment by bernardini687** [comment]
Makes sense... Yes, feel free to open the issues!

**Comment by bernardini687** [comment]
here you go, i've made the update :) (https://wsabi.itch.io/focus/devlog/480063/version-11)
